spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eventcenter
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    server:
      port: 8080
